// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa0sNNdJjdyqQ1yqzQP_8fVqr8QLU3W0g',
    appId: '1:799389945462:web:a878b477bc6231f4875957',
    messagingSenderId: '799389945462',
    projectId: 'spot-32b4e',
    authDomain: 'spot-32b4e.firebaseapp.com',
    storageBucket: 'spot-32b4e.firebasestorage.app',
    measurementId: 'G-VP66L5LFJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoo2SDYGADZ6bhSjfE3M55dACWybQZoR8',
    appId: '1:799389945462:android:148770134f835aac875957',
    messagingSenderId: '799389945462',
    projectId: 'spot-32b4e',
    storageBucket: 'spot-32b4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsF-oaOj4cLk3Qw5EqAYgNv8iUtMZfAJk',
    appId: '1:799389945462:ios:47e19a230af22dd3875957',
    messagingSenderId: '799389945462',
    projectId: 'spot-32b4e',
    storageBucket: 'spot-32b4e.firebasestorage.app',
    iosBundleId: 'com.enliven.spot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsF-oaOj4cLk3Qw5EqAYgNv8iUtMZfAJk',
    appId: '1:799389945462:ios:47e19a230af22dd3875957',
    messagingSenderId: '799389945462',
    projectId: 'spot-32b4e',
    storageBucket: 'spot-32b4e.firebasestorage.app',
    iosBundleId: 'com.enliven.spot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa0sNNdJjdyqQ1yqzQP_8fVqr8QLU3W0g',
    appId: '1:799389945462:web:b459cc1312317bce875957',
    messagingSenderId: '799389945462',
    projectId: 'spot-32b4e',
    authDomain: 'spot-32b4e.firebaseapp.com',
    storageBucket: 'spot-32b4e.firebasestorage.app',
    measurementId: 'G-CCHB7MCRS8',
  );
}
